[build]
builder = "NIXPACKS"
buildCommand = "cd time-off-service && npm install && npm run build"

[deploy]
startCommand = "cd time-off-service && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
